/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as UserIndexImport } from './routes/user/index'
import { Route as UserLikesIndexImport } from './routes/user/likes/index'
import { Route as GamesMisteryDogsIndexImport } from './routes/games/mistery-dogs/index'
import { Route as GamesBreedGuesserIndexImport } from './routes/games/breed-guesser/index'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const UserIndexRoute = UserIndexImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRoute,
} as any)

const UserLikesIndexRoute = UserLikesIndexImport.update({
  id: '/user/likes/',
  path: '/user/likes/',
  getParentRoute: () => rootRoute,
} as any)

const GamesMisteryDogsIndexRoute = GamesMisteryDogsIndexImport.update({
  id: '/games/mistery-dogs/',
  path: '/games/mistery-dogs/',
  getParentRoute: () => rootRoute,
} as any)

const GamesBreedGuesserIndexRoute = GamesBreedGuesserIndexImport.update({
  id: '/games/breed-guesser/',
  path: '/games/breed-guesser/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserIndexImport
      parentRoute: typeof rootRoute
    }
    '/games/breed-guesser/': {
      id: '/games/breed-guesser/'
      path: '/games/breed-guesser'
      fullPath: '/games/breed-guesser'
      preLoaderRoute: typeof GamesBreedGuesserIndexImport
      parentRoute: typeof rootRoute
    }
    '/games/mistery-dogs/': {
      id: '/games/mistery-dogs/'
      path: '/games/mistery-dogs'
      fullPath: '/games/mistery-dogs'
      preLoaderRoute: typeof GamesMisteryDogsIndexImport
      parentRoute: typeof rootRoute
    }
    '/user/likes/': {
      id: '/user/likes/'
      path: '/user/likes'
      fullPath: '/user/likes'
      preLoaderRoute: typeof UserLikesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/user': typeof UserIndexRoute
  '/games/breed-guesser': typeof GamesBreedGuesserIndexRoute
  '/games/mistery-dogs': typeof GamesMisteryDogsIndexRoute
  '/user/likes': typeof UserLikesIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/user': typeof UserIndexRoute
  '/games/breed-guesser': typeof GamesBreedGuesserIndexRoute
  '/games/mistery-dogs': typeof GamesMisteryDogsIndexRoute
  '/user/likes': typeof UserLikesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/user/': typeof UserIndexRoute
  '/games/breed-guesser/': typeof GamesBreedGuesserIndexRoute
  '/games/mistery-dogs/': typeof GamesMisteryDogsIndexRoute
  '/user/likes/': typeof UserLikesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/user'
    | '/games/breed-guesser'
    | '/games/mistery-dogs'
    | '/user/likes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/user'
    | '/games/breed-guesser'
    | '/games/mistery-dogs'
    | '/user/likes'
  id:
    | '__root__'
    | '/login'
    | '/signup'
    | '/user/'
    | '/games/breed-guesser/'
    | '/games/mistery-dogs/'
    | '/user/likes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UserIndexRoute: typeof UserIndexRoute
  GamesBreedGuesserIndexRoute: typeof GamesBreedGuesserIndexRoute
  GamesMisteryDogsIndexRoute: typeof GamesMisteryDogsIndexRoute
  UserLikesIndexRoute: typeof UserLikesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UserIndexRoute: UserIndexRoute,
  GamesBreedGuesserIndexRoute: GamesBreedGuesserIndexRoute,
  GamesMisteryDogsIndexRoute: GamesMisteryDogsIndexRoute,
  UserLikesIndexRoute: UserLikesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/login",
        "/signup",
        "/user/",
        "/games/breed-guesser/",
        "/games/mistery-dogs/",
        "/user/likes/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/user/": {
      "filePath": "user/index.tsx"
    },
    "/games/breed-guesser/": {
      "filePath": "games/breed-guesser/index.tsx"
    },
    "/games/mistery-dogs/": {
      "filePath": "games/mistery-dogs/index.tsx"
    },
    "/user/likes/": {
      "filePath": "user/likes/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
